import taxonomy from "../../shared/taxonomy.json";
import type { Concept, Locale } from "./model";
export const words = {
  cn: { manage: "管理视图", manageTitle: "Concept 管理", manageSubtitle: "浏览目录并维护中英文内容、草稿与归档词条。", create: "新建 Concept", search: "搜索名称、别名、描述或标签", all: "全部状态", draft: "草稿", browsable: "可浏览", recommended: "可推荐", archived: "已归档", tag: "标签", domain: "领域", intent: "意图", result: "条结果", pageSize: "每页显示", previousPage: "上一页", nextPage: "下一页", pageOf: "第", ofPages: "页，共", empty: "当前没有符合条件的 Concept", edit: "编辑", preview: "预览", delete: "删除", permanentlyDelete: "永久删除", source: "出处", missing: "待补字段", noImage: "暂无图片", actions: "操作", chooseDomains: "选择领域", selectedDomains: "个领域已选", chooseIntents: "选择意图", selectedIntents: "个意图已选", confirm: "确认", cancel: "取消", selectDomainHint: "勾选需要的领域，确认后回填。", selectIntentHint: "勾选需要的意图，确认后回填。", name: "名称", aliases: "别名（逗号分隔）", description: "描述", sourceText: "出处文本", tags: "标签（逗号分隔）", wiki: "Wiki 链接（可选）", trigger: "触发场景（逗号分隔）", avoid: "避免使用情况（逗号分隔）", transform: "转化目标（逗号分隔）", instruction: "Agent 指令", browse: "可浏览", recommend: "可推荐", draftStatus: "草稿", browseMissing: "浏览条件待补", recommendMissing: "推荐条件待补", none: "无", image: "WebP 图片", defaultImage: "使用默认配图", saveBeforeImage: "保存草稿后可添加图片", remove: "移除", idLabel: "ID · 固定标识", newRecord: "新建记录", conceptLabel: "Concept", close: "关闭", save: "保存", saving: "保存中…", cancelLabel: "取消", interactionType: "交互类型", epistemicType: "认识类型", unspecified: "未指定" },
  en: { manage: "Manage Concepts", manageTitle: "Manage Concepts", manageSubtitle: "Browse the registry and maintain both languages, drafts, and archived Concepts.", create: "New Concept", search: "Search name, aliases, description or tags", all: "All statuses", draft: "Draft", browsable: "Browsable", recommended: "Recommendable", archived: "Archived", tag: "Tag", domain: "Domain", intent: "Intent", result: "results", pageSize: "Items per page", previousPage: "Previous", nextPage: "Next", pageOf: "Page", ofPages: "of", empty: "No Concepts match these filters", edit: "Edit", preview: "Preview", delete: "Delete", permanentlyDelete: "Permanently delete", source: "Source", missing: "Missing fields", noImage: "No image", actions: "Actions", chooseDomains: "Choose domains", selectedDomains: "domains selected", chooseIntents: "Choose intents", selectedIntents: "intents selected", confirm: "Confirm", cancel: "Cancel", selectDomainHint: "Check the domains you need, then confirm.", selectIntentHint: "Check the intents you need, then confirm.", name: "Name", aliases: "Aliases · comma separated", description: "Description", sourceText: "Source text", tags: "Tags · comma separated", wiki: "Wiki URL · optional", trigger: "Trigger scenarios · comma separated", avoid: "Avoid when · comma separated", transform: "Transform goals · comma separated", instruction: "Agent instruction", browse: "Browsable", recommend: "Recommendable", draftStatus: "Draft", browseMissing: "Browse missing", recommendMissing: "Recommend missing", none: "none", image: "WebP images", defaultImage: "Using default cover", saveBeforeImage: "Save the draft before adding an image.", remove: "Remove", idLabel: "ID · immutable slug", newRecord: "New record", conceptLabel: "Concept", close: "Close", save: "Save", saving: "Saving…", cancelLabel: "Cancel", interactionType: "Interaction type", epistemicType: "Epistemic type", unspecified: "Unspecified" },
};
export const typeNames: Record<string, Record<Locale, string>> = Object.fromEntries(
  [...taxonomy.interaction_types, ...taxonomy.epistemic_types].map(({ code, cn, en }) => [code, { cn, en }]),
);
export const labelsFor = (concept: Concept, locale: Locale) => [concept.interaction_type, concept.epistemic_type].filter((value): value is string => Boolean(value)).map((value) => typeNames[value]?.[locale] ?? value);

