import { RefreshCw } from "lucide-react";
import type { DashboardData, Locale } from "./model";
export default function DashboardView({ data, error, locale, onRefresh }: { data: DashboardData | null; error: string; locale: Locale; onRefresh: () => void }) {
  const cn = locale === "cn";
  const metric = (label: string, value: number) => <div className="rounded-2xl border border-slate-200 bg-white p-5"><p className="text-xs text-slate-500">{label}</p><p className="mt-3 text-3xl font-semibold text-emerald-950">{value}</p></div>;
  return <section className="py-8" aria-label="Dashboard">
    <div className="flex flex-wrap items-start justify-between gap-4"><div><p className="mb-2 text-[11px] font-semibold uppercase tracking-[.18em] text-emerald-800">Concept Registry</p><h1 className="text-3xl font-semibold tracking-tight">Dashboard</h1><p className="mt-2 text-sm text-slate-500">{cn ? "实时目录数量与修订，来自同一份本地 Registry。" : "Live catalog counts and revisions from the same local Registry."}</p></div><button onClick={onRefresh} className="inline-flex items-center gap-2 rounded-lg border border-slate-200 bg-white px-3 py-2 text-sm"><RefreshCw size={15} />{cn ? "刷新" : "Refresh"}</button></div>
    {error && <p role="alert" className="mt-5 rounded-lg bg-rose-50 px-4 py-3 text-sm text-rose-800">{error}</p>}
    {!data ? <p className="mt-8 text-sm text-slate-500">{cn ? "读取中…" : "Loading…"}</p> : <>
      <div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{metric(cn ? "活跃 Concept" : "Active Concepts", data.active_total)}{metric(cn ? "双语均为草稿" : "Draft in both locales", data.both_draft)}{metric(cn ? "归档 Concept" : "Archived Concepts", data.archived_total)}</div>
      <div className="mt-8 grid gap-4 md:grid-cols-2">{(["cn", "en"] as const).map((language) => <div key={language} className="rounded-2xl border border-slate-200 bg-white p-5"><h2 className="font-semibold">{language === "cn" ? "中文 · cn" : "English · en"}</h2><dl className="mt-4 grid grid-cols-2 gap-3"><div className="rounded-xl bg-emerald-50 p-4"><dt className="text-xs text-emerald-900">{cn ? "可浏览" : "Browsable"}</dt><dd className="mt-2 text-2xl font-semibold">{data.locales[language].browsable}</dd></div><div className="rounded-xl bg-emerald-50 p-4"><dt className="text-xs text-emerald-900">{cn ? "可推荐" : "Recommendable"}</dt><dd className="mt-2 text-2xl font-semibold">{data.locales[language].recommendable}</dd></div></dl></div>)}</div>
      <p className="mt-3 text-xs text-slate-500">{cn ? "同一 Concept 可同时计入 cn 与 en；两列不可相加作为去重总数。" : "A Concept can count in both cn and en; do not add the locale counts as a unique total."}</p>
      <div className="mt-8 rounded-2xl border border-slate-200 bg-white p-5"><h2 className="font-semibold">{cn ? "最近修订" : "Recent revisions"}</h2>{data.recent_revisions.length === 0 ? <p className="mt-4 text-sm text-slate-500">{cn ? "暂无修订" : "No revisions"}</p> : <ul className="mt-4 divide-y divide-slate-100">{data.recent_revisions.map((revision) => <li key={revision.revision_id} className="flex flex-wrap items-start justify-between gap-2 py-3 text-sm"><div><span className="font-medium">{revision.concept_id}</span><span className="ml-2 text-slate-500">v{revision.version} · {revision.operation}</span><p className="mt-1 text-xs text-slate-500">{cn ? "影响语言" : "Locales"}: {revision.affected_languages.join(", ") || (cn ? "共用字段" : "shared fields")}{revision.shared_changes && revision.affected_languages.length > 0 ? (cn ? " · 含共用字段" : " · includes shared fields") : ""}</p></div><time dateTime={revision.changed_at} className="text-xs text-slate-500">{new Date(revision.changed_at).toLocaleString()}</time></li>)}</ul>}</div>
      <section className="mt-8" aria-label="Skill usage"><h2 className="font-semibold">{cn ? "Skill 使用与反馈" : "Skill usage and feedback"}</h2><p className="mt-2 text-xs text-slate-500">{cn ? "只统计主动调用 Skill 的事件；推荐按 Concept 次数，空推荐按调用次数。离线 Eval 不计入。" : "Only explicit Skill events; recommendations count Concepts, NONE counts runs. Offline Eval is excluded."}</p><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{metric(cn ? "调用次数" : "Runs", data.usage.runs_total)}{metric(cn ? "空推荐次数" : "NONE runs", data.usage.none_runs)}{metric(cn ? "推荐次数" : "Recommended", data.usage.events.recommended)}{metric(cn ? "实际应用" : "Applied", data.usage.events.applied)}</div><div className="mt-3 grid gap-3 sm:grid-cols-3">{metric(cn ? "查看详情" : "Viewed", data.usage.events.viewed)}{metric(cn ? "忽略" : "Ignored", data.usage.events.ignored)}{metric(cn ? "无帮助" : "Not useful", data.usage.events.not_useful)}</div><div className="mt-4 grid gap-3 md:grid-cols-2">{(["cn", "en"] as const).map((language) => <div key={language} className="rounded-xl border border-slate-200 bg-white p-4 text-sm"><h3 className="font-medium">{language === "cn" ? "中文 · cn" : "English · en"}</h3><p className="mt-2 text-slate-600">{cn ? "调用 / 空推荐 / 推荐 / 应用" : "Runs / NONE / Recommended / Applied"}: {data.usage.locales[language].runs_total} / {data.usage.locales[language].none_runs} / {data.usage.locales[language].events.recommended} / {data.usage.locales[language].events.applied}</p></div>)}</div></section>
    </>}
  </section>;
}
